### ISSUE TITLE
有些栏目下载不了

### ISSUE THREAD

**Issue by WizzXu** [MwumLi/gktimesc2gitbook#1]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.res.on (/usr/local/lib/node_modules/gktimesc2gitbook/lib/index.js:32:40)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

异常信息

**Comment by MwumLi** [comment]
看错误是调用极客时间那边的接口，返回了非 json 信息，提供一下专栏信息

**Comment by WizzXu** [comment]
142 Android开发高手课

**Comment by MwumLi** [comment]
@AerialLadder 没问题呀, 如下图
![image](https://user-images.githubusercontent.com/6889433/62338107-d5ee2d00-b509-11e9-9a71-e1c35e842746.png)
生成的 gitbook site:  
![image](https://user-images.githubusercontent.com/6889433/62338250-662c7200-b50a-11e9-9695-2c1c77118ad7.png)

你按照我的步骤试一下:  

1. 新建一个文件 `gitbook.json`:  (我没有购买，所以 cookie 有无都没关系，反正只能看到一部分)
```
{
  "cid": 142,
  "cookie": ""
}
```
2. 执行下载命令: `npx gktimesc2gitbook ./gitbook.json`  
    默认会导出当前目录的 `./gitbook/` 下面

**Comment by WeihanLi** [comment]
126 数据结构与算法之美 也有类似的问题

没有 cookie 的时候是正常的，带着 cookie 会有问题

**Comment by MwumLi** [comment]
@WeihanLi 你在试一下  
我今天也发现问题了，是极客时间那边的接口访问的客户端做了限制，我刚刚做了修复支持, 具体见 [28f7c6b](https://github.com/MwumLi/gktimesc2gitbook/commit/28f7c6bafea82ea7787dbd5a3338560061643c7c)

**Comment by MwumLi** [comment]
@AerialLadder 之前你没下载成功，应该一样问题，可以在试一下

**Comment by WeihanLi** [comment]
刚才用了 1.0.2 版本，还是有问题（截图一直上传不上去...

> 将生成书籍到 C:\projects\test\temp\gitbook ...
[Generated] book.json
[Generated] README.md
[Generated] SUMMARY.md ...
[Generate] docs ...
undefined:1
>
> SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\liweihan\AppData\Roaming\npm\node_modules\gktimesc2gitbook\lib\index.js:33:40)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1137:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by MwumLi** [comment]
@WeihanLi 同学，真的可以下载，我刚刚下载了这个专栏, 如图
![image](https://user-images.githubusercontent.com/6889433/66703847-6f775d80-ed49-11e9-9b8b-019b28729642.png)
我建议你全局安装一下, 然后再试一下, 使用 `npx` 这种方式可能有缓存，你直接使用 github 上的版本 `npx github:MwumLi/gktimesc2gitbook ./gitbook.json`

**Comment by MwumLi** [comment]
@AerialLadder 晚上又重新找了一下问题，发现是因为极客时间对我们的请求做了速率控制，如果从一个客户端短时间发了大量请求，可能会认为我们在攻击它，从而限制请求。
我对了代码做了调整，增加了参数 `rate` 来控制请求速率，默认 500ms。  
你在用最新的版本试一下 `v1.0.3` , 选项丰富了一点，但是依旧可以和以前一样用
![image](https://user-images.githubusercontent.com/6889433/66707324-3e128800-ed71-11e9-9c44-60a14530568a.png)

**Comment by MwumLi** [comment]
@AerialLadder 解决你的问题了吗？
