### ISSUE TITLE
有个重大问题会删除用户文件夹

### ISSUE THREAD

**Issue by slemon** [MwumLi/gktimesc2gitbook#12]
如果把路径设置成 /Users/xxxxx/Desktop/，就会删除（替换）整个文件夹

async function exportGitbook(cid, { gitbook, rate}) {
  let intro = await gktimeService.getColumnIntro(cid);
  let menus = await gktimeService.getColumnMenus(cid, intro.article_count);
  // clear
  sh.rm('-rf', gitbook);
...
}

**Comment by slemon** [comment]
`async function exportGitbook(cid, { gitbook, rate}) {
  let intro = await gktimeService.getColumnIntro(cid);
  let menus = await gktimeService.getColumnMenus(cid, intro.article_count);
  // clear
  sh.rm('-rf', gitbook);`

**Comment by MwumLi** [comment]
这属于用户体验更好的问题: 提示是否清空?   
对我来说, 这只是一个小工具, 暂时没有精力投入到这种细节, 我在 README 上添加以下提示
![image](https://user-images.githubusercontent.com/6889433/187333792-2e09337e-68e5-4024-a538-195021a5adb3.png)  

如果你有精力, 可以提 PR 过来
