### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by farss** [MwumLi/gktimesc2gitbook#2]

**Comment by MwumLi** [comment]
可以用呀，如图 
![image](https://user-images.githubusercontent.com/6889433/65043834-510e8400-d98e-11e9-9448-f4ebd9f261f5.png)
如不能用，请提供详细细节

**Comment by MwumLi** [comment]
@farss 我今天发了在添加 cookie 的情况下载，可能会出下载错误的问题，最终发现原因是因为极客时间那边对请求客户端做了限制，这个问题我已经修复了，你可以再试试重新下载
