### ISSUE TITLE
Error: 获取已购买专栏列表失败，请检查 cookie 信息是否正确

### ISSUE THREAD

**Issue by diesang** [MwumLi/gktimesc2gitbook#8]
我的cookie是从chrome里面复制出来的，应该是没错的，因为我用另一个工具填同样的cookie都可以下载到东西

**Comment by MwumLi** [comment]
额, 不太清楚, 我好像没啥问题
![image](https://user-images.githubusercontent.com/6889433/100459367-5625a200-3100-11eb-8e3e-c1384aa5c50f.png)
是不是获取的方式有问题, 我是登录之后, 打开开发者工具, 刷新页面, 粘贴任意一个请求的请求头的 cookie   
![image](https://user-images.githubusercontent.com/6889433/100459740-ef54b880-3100-11eb-9ef1-fa3779e477e6.png)
